config/routes.rb
Rails.application.routes.draw do
  # Se definen las rutas para los 3 archivos del proyecto
  get 'pages/home'
  get 'pages/projects'
  get 'pages/contact'

  # Se define como raíz home
  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def projects
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Desafioevaluado</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%# Se agrega CDN de Bootstrap %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    
  </head>

  <body>
  <%# Se agrega una Navbar para que aparezca en todas las vistas %>
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ">
        <li class="nav-item botonesnav" >
          <%= link_to 'Home', pages_home_path %>
        </li>
        <li class="nav-item botonesnav" >
          <%= link_to 'Projects', pages_projects_path %>
        </li>
        <li class="nav-item botonesnav" >
          <%= link_to 'Contact', pages_contact_path %>
        </li>        
      </ul>
    </div>
  </div>
</nav>

    <%= yield %>

  </body>
  <%# Se agrega Script de Bootstrap %>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</html>

app/views/pages/contact.html.erb
    <%# Se crea el archivo con el comando rails g controller pages %>
<h2>Contacto:</h2>
<h3>Email: tomasperezg@gmail.com</h3>
<h3>Github: https://github.com/TomasPerezGonz</h3>
<h3>Linkedin: www.linkedin.com/in/tomas-alejandro-perez-gonzalez-94ba1194</h3>

app/views/pages/home.html.erb
<%# Se crea el archivo con el comando rails g controller pages %>
<h1>Bienvenido al Home del proyecto</h1>

app/views/pages/projects.html.erb
<%# Se crea el archivo con el comando rails g controller pages %>
<%# Se agrega desde Bootstrap codigo para tres elementos card %>

<div class="card-group">
  <div class="card">
    <%= image_tag 'viajeschile.jpg'%>
    <div class="card-body">
      <h5 class="card-title">Viajes Chile</h5>
      <p class="card-text">Proyecho en HTML subido a Github</p>      
    </div>
  </div>
  <div class="card">
    <%= image_tag 'refactorizacion.jpg', class:"acomodarImagen"%>
    <div class="card-body">
      <h5 class="card-title">Prueba Herencias</h5>
      <p class="card-text">Trabajo de refactorización utilizando herencia y polimorfismo en ruby</p>      
    </div>
  </div>
  <div class="card">
    <%= image_tag 'landing.jpg'%>
    <div class="card-body">
      <h5 class="card-title">Landing</h5>
      <p class="card-text">Proyecho en HTML subido a Github</p>
     
    </div>
  </div>
</div>